stages:
  - name: Unit test
    if: type IN (push)
jobs:
  include:
    - stage: Unit test
      language: node_js
      node_js: 6
      cache:
        directories:
        - node_modules
      before_install:
      - npm i -g yarn
      install:
      - yarn install
      script:
      - npm run test